### ISSUE TITLE
automations.yaml

### ISSUE THREAD

**Issue by iorifly** [iorifly/homeassistantbackup#1]
```
- id: '1527476913431'
  alias: Kodi Play seriado
  trigger:
  - entity_id: media_player.kodi
    from: idle
    platform: state
    to: playing
  condition:
  - condition: template
    value_template: '{{ states.media_player.kodi.attributes.media_content_type ==
      "tvshow" }}'
  - condition: state
    entity_id: sun.sun
    state: ' below_horizon'
  action:
  - data:
      event: luz-sala-principal-off
    service: ifttt.trigger
- id: '1527477488068'
  alias: kodi play filme
  trigger:
  - entity_id: media_player.kodi
    from: idle
    platform: state
    to: playing
  condition:
  - condition: template
    value_template: '{{ states.media_player.kodi.attributes.media_content_type ==
      "movie" }}'
  - condition: state
    entity_id: sun.sun
    state: ' below_horizon'
  action:
  - data:
      event: luz-sala-todas-off
    service: ifttt.trigger
- id: '1527478719908'
  alias: kodi stop
  trigger:
  - entity_id: media_player.kodi
    from: playing
    platform: state
    to: idle
  condition:
  - condition: state
    entity_id: sun.sun
    state: below_horizon
  action:
  - data:
      event: luz-sala-todas-on
    service: ifttt.trigger
- id: '1527478899417'
  alias: Kodi play Musica
  trigger:
  - entity_id: media_player.kodi
    from: idle
    platform: state
    to: playing
  condition:
  - condition: template
    value_template: '{{ states.media_player.kodi.attributes.media_content_type ==
      "music" }}'
  action:
  - alias: ''
    data: {}
    service: automation.turn_off
    entity_id:
    - automation.kodi_stop
- id: '1527553034389'
  alias: kodi stop2
  trigger:
  - entity_id: media_player.kodi
    from: playing
    platform: state
    to: idle
  condition: []
  action:
  - service: automation.turn_on
    entity_id:
    - automation.kodi_stop
- id: '1527554908381'
  alias: kodi pause
  trigger:
  - entity_id: media_player.kodi
    from: playing
    platform: state
    to: paused
  condition:
  - condition: state
    entity_id: sun.sun
    state: below_horizon
  action:
  - data:
      event: luz-sala-home-on
    service: ifttt.trigger
- id: '1527555010284'
  alias: kodi paused para playing
  trigger:
  - entity_id: media_player.kodi
    from: paused
    platform: state
    to: playing
  condition: []
  action:
  - data:
      event: luz-sala-home-off
    service: ifttt.trigger
- id: '1527812884401'
  alias: tocando music para filme
  trigger:
  - entity_id: media_player.kodi
    from: playing
    platform: state
    to: playing
  - platform: template
    value_template: '{{ states.media_player.kodi.attributes.media_content_type ==
      "movie" }}'
  condition: []
  action:
  - data:
      event: luz-sala-todas-off
    service: ifttt.trigger
  - service: automation.turn_on
    entity_id:
    - automation.kodi_stop
- id: '1527819129627'
  alias: tocando musica para seriado
  trigger:
  - entity_id: media_player.kodi
    from: playing
    platform: state
    to: playing
  - platform: template
    value_template: '{{ states.media_player.kodi.attributes.media_content_type ==
      "tvshow" }}'
  condition: []
  action:
  - data:
      event: luz-sala-principal-off
    service: ifttt.trigger
  - service: automation.turn_on
    entity_id:
    - automation.kodi_stop
- id: '1527909440756'
  alias: Desligar luz Piscina
  trigger:
  - entity_id: input_boolean.sonoff_switch_5
    from: 'on'
    platform: state
    to: 'off'
  condition: []
  action:
  - data:
      event: DesligarLuzPiscina
    service: ifttt.trigger
- id: '1527909570246'
  alias: LigandoLuzPiscina
  trigger:
  - entity_id: input_boolean.sonoff_switch_5
    from: 'off'
    platform: state
    to: 'on'
  condition: []
  action:
  - data:
      event: LigandoLuzPiscina
    service: ifttt.trigger
- id: '1527909847949'
  alias: Liga Todas luzes Sala
  trigger:
  - entity_id: group.main_device_group
    from: 'off'
    platform: state
    to: 'on'
  condition: []
  action:
  - data:
      event: luz-sala-todas-on
    service: ifttt.trigger
- id: '1527910040896'
  alias: Desligar Todas Luzes Sala
  trigger:
  - entity_id: group.main_device_group
    from: 'on'
    platform: state
    to: 'off'
  condition: []
  action:
  - data:
      event: luz-sala-todas-off
    service: ifttt.trigger

```

**Comment by iorifly** [comment]
```
- id: '1527960915671'
  alias: Cafeteira Ausentes Juliana e Eu
  trigger:
  - entity_id: device_tracker.juliana_iphone
    from: home
    platform: state
    to: not_home
  - entity_id: device_tracker.renato_iphone
    from: home
    platform: state
    to: not_home
  condition: []
  action:
  - data:
      event: DesligarCafeteira
    service: ifttt.trigger
- id: '1527476913431'
  alias: Kodi Play seriado
  trigger:
  - entity_id: media_player.kodi
    from: idle
    platform: state
    to: playing
  condition:
  - condition: template
    value_template: '{{ states.media_player.kodi.attributes.media_content_type ==
      "tvshow" }}'
  - condition: state
    entity_id: sun.sun
    state: ' below_horizon'
  action:
  - data:
      event: luz-sala-principal-off
    service: ifttt.trigger
- id: '1527477488068'
  alias: kodi play filme
  trigger:
  - entity_id: media_player.kodi
    from: idle
    platform: state
    to: playing
  condition:
  - condition: template
    value_template: '{{ states.media_player.kodi.attributes.media_content_type ==
      "movie" }}'
  - condition: state
    entity_id: sun.sun
    state: ' below_horizon'
  action:
  - data:
      event: luz-sala-todas-off
    service: ifttt.trigger
- id: '1527478719908'
  alias: kodi stop
  trigger:
  - entity_id: media_player.kodi
    from: playing
    platform: state
    to: idle
  condition:
  - condition: state
    entity_id: sun.sun
    state: below_horizon
  action:
  - data:
      event: luz-sala-todas-on
    service: ifttt.trigger
- id: '1527478899417'
  alias: Kodi play Musica
  trigger:
  - entity_id: media_player.kodi
    from: idle
    platform: state
    to: playing
  condition:
  - condition: template
    value_template: '{{ states.media_player.kodi.attributes.media_content_type ==
      "music" }}'
  action:
  - alias: ''
    data: {}
    service: automation.turn_off
    entity_id:
    - automation.kodi_stop
- id: '1527553034389'
  alias: kodi stop2
  trigger:
  - entity_id: media_player.kodi
    from: playing
    platform: state
    to: idle
  condition: []
  action:
  - service: automation.turn_on
    entity_id:
    - automation.kodi_stop
- id: '1527554908381'
  alias: kodi pause
  trigger:
  - entity_id: media_player.kodi
    from: playing
    platform: state
    to: paused
  condition:
  - condition: state
    entity_id: sun.sun
    state: below_horizon
  action:
  - data:
      event: luz-sala-home-on
    service: ifttt.trigger
- id: '1527555010284'
  alias: kodi paused para playing
  trigger:
  - entity_id: media_player.kodi
    from: paused
    platform: state
    to: playing
  condition: []
  action:
  - data:
      event: luz-sala-home-off
    service: ifttt.trigger
- id: '1527812884401'
  alias: tocando music para filme
  trigger:
  - entity_id: media_player.kodi
    from: playing
    platform: state
    to: playing
  - platform: template
    value_template: '{{ states.media_player.kodi.attributes.media_content_type ==
      "movie" }}'
  condition: []
  action:
  - data:
      event: luz-sala-todas-off
    service: ifttt.trigger
  - service: automation.turn_on
    entity_id:
    - automation.kodi_stop
- id: '1527819129627'
  alias: tocando musica para seriado
  trigger:
  - entity_id: media_player.kodi
    from: playing
    platform: state
    to: playing
  - platform: template
    value_template: '{{ states.media_player.kodi.attributes.media_content_type ==
      "tvshow" }}'
  condition: []
  action:
  - data:
      event: luz-sala-principal-off
    service: ifttt.trigger
  - service: automation.turn_on
    entity_id:
    - automation.kodi_stop
- id: '1527909440756'
  alias: Desligar luz Piscina
  trigger:
  - entity_id: input_boolean.sonoff_switch_5
    from: 'on'
    platform: state
    to: 'off'
  condition: []
  action:
  - data:
      event: DesligarLuzPiscina
    service: ifttt.trigger
- id: '1527909570246'
  alias: LigandoLuzPiscina
  trigger:
  - entity_id: input_boolean.sonoff_switch_5
    from: 'off'
    platform: state
    to: 'on'
  condition: []
  action:
  - data:
      event: LigandoLuzPiscina
    service: ifttt.trigger
- id: '1527909847949'
  alias: Liga Todas luzes Sala
  trigger:
  - entity_id: group.main_device_group
    from: 'off'
    platform: state
    to: 'on'
  condition: []
  action:
  - data:
      event: luz-sala-todas-on
    service: ifttt.trigger
- id: '1527910040896'
  alias: Desligar Todas Luzes Sala
  trigger:
  - entity_id: group.main_device_group
    from: 'on'
    platform: state
    to: 'off'
  condition: []
  action:
  - data:
      event: luz-sala-todas-off
    service: ifttt.trigger
- id: '1527992309566'
  alias: Tv Desligada
  trigger:
  - entity_id: media_player.samsung_led75_un75h6300
    from: 'on'
    platform: state
    to: 'off'
  condition: []
  action:
  - data:
      event: luz-sala-entrada-on
    service: ifttt.trigger
  - delay: '00:00:20'
  - data:
      event: luz-sala-principal-on
    service: ifttt.trigger
  - delay: '00:03:00'
  - data:
      event: luz-sala-todas-off
    service: ifttt.trigger


```

**Comment by iorifly** [comment]
```
- id: '1527960915671'
  alias: Cafeteira Ausentes Juliana e Eu
  trigger:
  - entity_id: device_tracker.juliana_iphone
    from: home
    platform: state
    to: not_home
  - entity_id: device_tracker.renato_iphone
    from: home
    platform: state
    to: not_home
  condition: []
  action:
  - data:
      event: DesligarCafeteira
    service: ifttt.trigger
- id: '1527476913431'
  alias: Kodi Play seriado
  trigger:
  - entity_id: media_player.kodi
    from: idle
    platform: state
    to: playing
  condition:
  - condition: template
    value_template: '{{ states.media_player.kodi.attributes.media_content_type ==
      "tvshow" }}'
  - condition: state
    entity_id: sun.sun
    state: ' below_horizon'
  action:
  - data:
      event: luz-sala-principal-off
    service: ifttt.trigger
- id: '1527477488068'
  alias: kodi play filme
  trigger:
  - entity_id: media_player.kodi
    from: idle
    platform: state
    to: playing
  condition:
  - condition: template
    value_template: '{{ states.media_player.kodi.attributes.media_content_type ==
      "movie" }}'
  - condition: state
    entity_id: sun.sun
    state: ' below_horizon'
  action:
  - data:
      event: luz-sala-todas-off
    service: ifttt.trigger
- id: '1527478719908'
  alias: kodi stop
  trigger:
  - entity_id: media_player.kodi
    from: playing
    platform: state
    to: idle
  condition:
  - condition: state
    entity_id: sun.sun
    state: below_horizon
  action:
  - data:
      event: luz-sala-todas-on
    service: ifttt.trigger
- id: '1527478899417'
  alias: Kodi play Musica
  trigger:
  - entity_id: media_player.kodi
    from: idle
    platform: state
    to: playing
  condition:
  - condition: template
    value_template: '{{ states.media_player.kodi.attributes.media_content_type ==
      "music" }}'
  action:
  - alias: ''
    data: {}
    service: automation.turn_off
    entity_id:
    - automation.kodi_stop
- id: '1527553034389'
  alias: kodi stop2
  trigger:
  - entity_id: media_player.kodi
    from: playing
    platform: state
    to: idle
  condition: []
  action:
  - service: automation.turn_on
    entity_id:
    - automation.kodi_stop
- id: '1527554908381'
  alias: kodi pause
  trigger:
  - entity_id: media_player.kodi
    from: playing
    platform: state
    to: paused
  condition:
  - condition: state
    entity_id: sun.sun
    state: below_horizon
  action:
  - data:
      event: luz-sala-home-on
    service: ifttt.trigger
- id: '1527555010284'
  alias: kodi paused para playing
  trigger:
  - entity_id: media_player.kodi
    from: paused
    platform: state
    to: playing
  condition: []
  action:
  - data:
      event: luz-sala-home-off
    service: ifttt.trigger
- id: '1527812884401'
  alias: tocando music para filme
  trigger:
  - entity_id: media_player.kodi
    from: playing
    platform: state
    to: playing
  - platform: template
    value_template: '{{ states.media_player.kodi.attributes.media_content_type ==
      "movie" }}'
  condition: []
  action:
  - data:
      event: luz-sala-todas-off
    service: ifttt.trigger
  - service: automation.turn_on
    entity_id:
    - automation.kodi_stop
- id: '1527819129627'
  alias: tocando musica para seriado
  trigger:
  - entity_id: media_player.kodi
    from: playing
    platform: state
    to: playing
  - platform: template
    value_template: '{{ states.media_player.kodi.attributes.media_content_type ==
      "tvshow" }}'
  condition: []
  action:
  - data:
      event: luz-sala-principal-off
    service: ifttt.trigger
  - service: automation.turn_on
    entity_id:
    - automation.kodi_stop
- id: '1527909440756'
  alias: Desligar luz Piscina
  trigger:
  - entity_id: input_boolean.sonoff_switch_5
    from: 'on'
    platform: state
    to: 'off'
  condition: []
  action:
  - data:
      event: DesligarLuzPiscina
    service: ifttt.trigger
- id: '1527909570246'
  alias: LigandoLuzPiscina
  trigger:
  - entity_id: input_boolean.sonoff_switch_5
    from: 'off'
    platform: state
    to: 'on'
  condition: []
  action:
  - data:
      event: LigandoLuzPiscina
    service: ifttt.trigger
- id: '1527909847949'
  alias: Liga Todas luzes Sala
  trigger:
  - entity_id: group.main_device_group
    from: 'off'
    platform: state
    to: 'on'
  condition: []
  action:
  - data:
      event: luz-sala-todas-on
    service: ifttt.trigger
- id: '1527910040896'
  alias: Desligar Todas Luzes Sala
  trigger:
  - entity_id: group.main_device_group
    from: 'on'
    platform: state
    to: 'off'
  condition: []
  action:
  - data:
      event: luz-sala-todas-off
    service: ifttt.trigger
- id: '1527992309566'
  alias: Tv Desligada
  trigger:
  - entity_id: media_player.samsung_led75_un75h6300
    from: 'on'
    platform: state
    to: 'off'
  condition:
  - condition: state
    entity_id: sun.sun
    state: below_horizon
  action:
  - data:
      event: luz-sala-entrada-on
    service: ifttt.trigger
  - delay: 00:00:10
  - data:
      event: luz-sala-principal-on
    service: ifttt.trigger
  - delay: 00:02:00
  - data:
      event: luz-sala-todas-off
    service: ifttt.trigger
- id: '1528063237091'
  alias: Juliana E Renato Chegando Luz entrada
  trigger:
  - entity_id: device_tracker.juliana_iphone
    from: not_home
    platform: state
    to: home
  - entity_id: device_tracker.renato_iphone
    from: not_home
    platform: state
    to: home
  condition:
  - condition: state
    entity_id: sun.sun
    state: below_horizon
  action:
  - data:
      event: luz-sala-entrada-on
    service: ifttt.trigger
- id: '1528075569700'
  alias: Fecha o kodi
  trigger:
  - entity_id: media_player.kodi
    from: idle
    platform: state
    to: 'off'
  condition:
  - condition: state
    entity_id: sun.sun
    state: below_horizon
  action:
  - data:
      event: luz-sala-home-off
    service: ifttt.trigger
  - data:
      event: luz-sala-principal-off
    service: ifttt.trigger
```

**Comment by iorifly** [comment]
```
- id: '1527960915671'
  alias: 'Cafeteira Ausentes Juliana e Renato '
  trigger:
  - entity_id: group.all_devices
    from: home
    platform: state
  condition: []
  action:
  - data:
      event: DesligarCafeteira
    service: ifttt.trigger
- id: '1527476913431'
  alias: Kodi Play seriado
  trigger:
  - entity_id: media_player.kodi
    from: idle
    platform: state
    to: playing
  condition:
  - condition: template
    value_template: '{{ states.media_player.kodi.attributes.media_content_type ==
      "tvshow" }}'
  action:
  - data:
      event: luz-sala-principal-off
    service: ifttt.trigger
  - entity_id:
    - automation.kodi_stop
    service: automation.turn_off
- id: '1527477488068'
  alias: kodi play filme
  trigger:
  - entity_id: media_player.kodi
    from: idle
    platform: state
    to: playing
  condition:
  - condition: template
    value_template: '{{ states.media_player.kodi.attributes.media_content_type ==
      "movie" }}'
  - condition: state
    entity_id: sun.sun
    state: ' below_horizon'
  action:
  - data:
      event: luz-sala-todas-off
    service: ifttt.trigger
- id: '1527478719908'
  alias: kodi stop
  trigger:
  - entity_id: media_player.kodi
    from: playing
    platform: state
    to: idle
  - entity_id: media_player.kodi
    from: paused
    platform: state
    to: idle
  condition:
  - condition: state
    entity_id: sun.sun
    state: below_horizon
  action:
  - data:
      event: luz-sala-todas-on
    service: ifttt.trigger
- id: '1527478899417'
  alias: Kodi play Musica
  trigger:
  - entity_id: media_player.kodi
    from: idle
    platform: state
    to: playing
  condition:
  - condition: template
    value_template: '{{ states.media_player.kodi.attributes.media_content_type ==
      "music" }}'
  action:
  - alias: ''
    data: {}
    service: automation.turn_off
    entity_id:
    - automation.kodi_stop
- id: '1527553034389'
  alias: kodi stop2
  trigger:
  - entity_id: media_player.kodi
    from: playing
    platform: state
    to: idle
  condition: []
  action:
  - service: automation.turn_on
    entity_id:
    - automation.kodi_stop
- id: '1527554908381'
  alias: kodi pause
  trigger:
  - entity_id: media_player.kodi
    from: playing
    platform: state
    to: paused
  condition:
  - condition: state
    entity_id: sun.sun
    state: below_horizon
  action:
  - data:
      event: luz-sala-home-on
    service: ifttt.trigger
- id: '1527555010284'
  alias: kodi paused para playing
  trigger:
  - entity_id: media_player.kodi
    from: paused
    platform: state
    to: playing
  condition:
  - condition: template
    value_template: '{{ states.media_player.kodi.attributes.media_content_type ==
      "movie" }}'
  action:
  - data:
      event: luz-sala-home-off
    service: ifttt.trigger
- id: '1527812884401'
  alias: tocando music para filme
  trigger:
  - entity_id: media_player.kodi
    from: playing
    platform: state
    to: playing
  - platform: template
    value_template: '{{ states.media_player.kodi.attributes.media_content_type ==
      "movie" }}'
  condition: []
  action:
  - data:
      event: luz-sala-todas-off
    service: ifttt.trigger
  - service: automation.turn_on
    entity_id:
    - automation.kodi_stop
- id: '1527819129627'
  alias: tocando musica para seriado
  trigger:
  - entity_id: media_player.kodi
    from: playing
    platform: state
    to: playing
  - platform: template
    value_template: '{{ states.media_player.kodi.attributes.media_content_type ==
      "tvshow" }}'
  condition: []
  action:
  - data:
      event: luz-sala-principal-off
    service: ifttt.trigger
  - service: automation.turn_on
    entity_id:
    - automation.kodi_stop
- id: '1527909440756'
  alias: Desligar luz Piscina
  trigger:
  - entity_id: input_boolean.sonoff_switch_5
    from: 'on'
    platform: state
    to: 'off'
  condition: []
  action:
  - data:
      event: DesligarLuzPiscina
    service: ifttt.trigger
- id: '1527909570246'
  alias: LigandoLuzPiscina
  trigger:
  - entity_id: input_boolean.sonoff_switch_5
    from: 'off'
    platform: state
    to: 'on'
  condition: []
  action:
  - data:
      event: LigandoLuzPiscina
    service: ifttt.trigger
- id: '1527909847949'
  alias: Liga Todas luzes Sala
  trigger:
  - entity_id: group.main_device_group
    from: 'off'
    platform: state
    to: 'on'
  condition: []
  action:
  - data:
      event: luz-sala-todas-on
    service: ifttt.trigger
- id: '1527910040896'
  alias: Desligar Todas Luzes Sala
  trigger:
  - entity_id: group.main_device_group
    from: 'on'
    platform: state
    to: 'off'
  condition: []
  action:
  - data:
      event: luz-sala-todas-off
    service: ifttt.trigger
- id: '1527992309566'
  alias: Tv Desligada
  trigger:
  - entity_id: media_player.samsung_led75_un75h6300
    from: 'on'
    platform: state
    to: 'off'
  condition:
  - condition: state
    entity_id: sun.sun
    state: below_horizon
  action:
  - data:
      event: luz-sala-entrada-on
    service: ifttt.trigger
  - delay: 00:00:01
  - data:
      event: luz-sala-principal-on
    service: ifttt.trigger
  - delay: 00:00:50
  - data:
      event: luz-sala-todas-off
    service: ifttt.trigger
- id: '1528063237091'
  alias: Juliana  Chegando Luz entrada
  trigger:
  - entity_id: device_tracker.juliana_iphone
    platform: state
    to: home
  condition:
  - condition: state
    entity_id: sun.sun
    state: below_horizon
  action:
  - data:
      event: luz-sala-entrada-on
    service: ifttt.trigger
- id: '1528075569700'
  alias: Fecha o kodi
  trigger:
  - entity_id: media_player.kodi
    from: idle
    platform: state
    to: 'off'
  condition:
  - condition: state
    entity_id: sun.sun
    state: below_horizon
  action:
  - data:
      event: luz-sala-home-off
    service: ifttt.trigger
  - data:
      event: luz-sala-principal-off
    service: ifttt.trigger
- id: '1528163572881'
  alias: Abrir o Kodi acorda pc
  trigger:
  - entity_id: media_player.kodi
    from: 'off'
    platform: state
    to: idle
  condition: []
  action:
  - entity_id:
    - switch.pc_escritorio
    service: switch.turn_on
- id: '1528417178680'
  alias: Renato Chegando em casa luz entrada
  trigger:
  - entity_id: device_tracker.renato_iphone
    platform: state
    to: home
  condition:
  - condition: state
    entity_id: sun.sun
    state: below_horizon
  action:
  - data:
      event: luz-sala-entrada-on
    service: ifttt.trigger
- id: '1528931805762'
  alias: Abri o kodi
  trigger:
  - entity_id: media_player.kodi
    from: 'off'
    platform: state
    to: idle
  condition:
  - condition: state
    entity_id: sun.sun
    state: below_horizon
  action:
  - data:
      event: luz-sala-home-on
    service: ifttt.trigger
```
