### ISSUE TITLE
customize.yaml

### ISSUE THREAD

**Issue by iorifly** [iorifly/homeassistantbackup#3]
```
media_player.samsung_led75_un75h6300:
  hidden: true
light.60019488789d_1921681164:
  friendly_name: Fita Led
input_boolean.sonoff_switch_1:
  icon: mdi:lightbulb-outline
input_boolean.sonoff_switch_2:
  icon: mdi:lightbulb-outline
input_boolean.sonoff_switch_4:
  icon: mdi:lightbulb-outline
input_boolean.sonoff_switch_3:
  icon: mdi:lightbulb-outline
input_boolean.sonoff_switch_5:
  icon: mdi:lightbulb-outline
automation.desliga_luz_entrada:
  hidden: true
automation.desligar_todas_luzes_sala:
  hidden: true
automation.liga_todas_luzes_sala:
  hidden: true
automation.ligandoluzpiscina:
  hidden: true
automation.desligar_luz_piscina:
  hidden: true
```
