### ISSUE TITLE
groups.yaml

### ISSUE THREAD

**Issue by iorifly** [iorifly/homeassistantbackup#4]
```
quintal:
    name: quintal
    view: yes
    entities:
        - switch.quintal
        
        
sala:
    name: Sala
    view: yes
    entities:
        - media_player.kodi
        - media_player.spotify
        - input_boolean.sonoff_switch_1
        - input_boolean.sonoff_switch_2
        - input_boolean.sonoff_switch_3
        - input_boolean.sonoff_switch_4
        
main_device_group:
  name: Luzes da Sala
  entities:
  - input_boolean.sonoff_switch_1
  - input_boolean.sonoff_switch_2
  - input_boolean.sonoff_switch_3
  - input_boolean.sonoff_switch_4
  

Luzes_quintal:
  name: Luzes do Quintal
  entities:
        - switch.quintal
        - input_boolean.sonoff_switch_5

        
        
cozinha:
    name: Cozinha
    view: yes
    entities:
        

quarto_casal:

        name: Suite
        view: yes
        entities:
        
automacao:
    name: Automacoes
    view: yes
    entities:
        - automation.kodi_play
        - automation.kodi_pause
        - automation.kodi_pause_para_play
        - automation.kodi_stop
        - automation.todas_as_luzes_da_sala_off
        - automation.todas_luzes_sala_da_on
        - automation.desliga_luz_entrada
```
