### ISSUE TITLE
script.yaml

### ISSUE THREAD

**Issue by iorifly** [iorifly/homeassistantbackup#5]
```
'1528942102635':
  alias: kodi playing
  sequence:
  - data: {}
    service: media_player.media_play
    entity_id: media_player.kodi
'1529010504913':
  alias: kodi paused
  sequence:
  - data: {}
    service: media_player.media_pause
    entity_id: media_player.kodi
'1529010611103':
  alias: kodi stop
  sequence:
  - data: {}
    service: media_player.media_stop
    entity_id: media_player.kodi
```
